config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'budgets#index'
  resources :budgets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_writer :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validate :validate_username
  validates :username, presence: :true, uniqueness: { case_sensitive: false }

  has_many :budgets

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
      @budgets = Budget.all
    end

    def new
      @budget = Budget.new
    end

    def create
      current_user.budgets.create(budget_params)
      redirect_to root_path
    end

    private

    def budget_params
      params.require(:budget).permit(:month, :income, :extra_income, :actual_personal_savings,
                                     :actual_tfsa, :actual_rrsp
  )
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/index.html.erb
<div class="container">
  <h1>Welcome to my Budgetting App</h1>

  <% @budgets.each do |budget| %>
    <%= budget.month %>
    <%= budget.income %>
    <%= budget.extra_income %>

  <% end %>
</div>

app/views/budgets/new.html.erb
<div class="container">
  <br />
  <h1>Enter Your Budget Details</h1>

  <%= simple_form_for @budget do |f| %>
      <%= f.input :month %>
      <%= f.input :income %>
      <%= f.input :extra_income %>
      <br />
    
      <h1>Actual/Budget</h1>
      <p> Please add your info here this is a little message cause you people are stupid as hell </p>
      <br >
    

    <div class="container">
    <div class="row">

      <%= f.input :actual_personal_savings,
                  hint: "Add your monthly personal savings here" %>

      <%= f.input :actual_tfsa %>
      <%= f.input :actual_rrsp %>
      <%= f.input :actual_car_payment %>
      <%= f.input :actual_gas_transit %>
      <%= f.input :actual_rent_mortgage %>
      <%= f.input :actual_insurance %>
      <%= f.input :actual_utilities %>
      <%= f.input :actual_internet_cable %>
    </div>

    </div>
    <br />
    <%= f.submit 'Add Budget', class: 'btn btn-primary' %>

  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budgetter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'Budgetter', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item">
          <%= link_to 'New Budget', new_budget_path, class: 'navbar-brand' %>
        </li>
      </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
        <li class="nav-item">
      <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
        </li>       
      <% end %>
    </ul>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>